-- insert retailers
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (1, 'Retailer 1', 'RETAILER')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (2, 'Retailer 2', 'RETAILER')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (3, 'Retailer 3', 'RETAILER')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (4, 'Retailer 4', 'RETAILER')

-- insert factories
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (5, 'Factory 1', 'FACTORY')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (6, 'Factory 2', 'FACTORY')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (7, 'Factory 3', 'FACTORY')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (8, 'Factory 4', 'FACTORY')

-- insert producers
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (9, 'Producer 1', 'PRODUCER')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (10, 'Producer 2', 'PRODUCER')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (11, 'Producer 3', 'PRODUCER')
INSERT INTO ACTOR_ENTITY(ID, NAME, TYPE) VALUES (12, 'Producer 4', 'PRODUCER')